# Netlify configuration for React client

[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = "dist"
  
  # Node version and environment  
  environment = { NODE_VERSION = "20", NODE_ENV = "production" }

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://dapi.kakao.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://dapi.kakao.com"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML with shorter duration
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Deploy previews configuration
[context.deploy-preview]
  command = "npm run build"

# Branch deploys configuration  
[context.branch-deploy]
  command = "npm run build"